# Generated by Django 2.2.3 on 2019-07-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('src', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('alt', models.CharField(max_length=200)),
                ('broken', models.BooleanField(default=0)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('keywords', models.CharField(max_length=1000)),
                ('crawled', models.IntegerField(default=0)),
                ('broken', models.BooleanField(default=0)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
